Vag 6
biocarl/vag pull request #22
Opened 2023-04-05 14:58 UTC by neko5687

2023-04-06 15:04 UTC, Bohdoh requested changes
qr-code.service.ts hat auf zeile 12 eine Leerzeile. 
poll-presenter-component.html hat auf Zeile 26-28 Leerzeilen. Bitte beides löschen, sowas sammelt sich sonst an. Clean Code 💪

2023-04-08 12:50 UTC, biocarl commented
@neko5687 @Languste1 Habt ihr den Code ausprobiert bevor ihr die Story auf in-review geschoben habt? 🙃 Immer final alles testen bevor ihr andere dazu holt! Bitte noch den letzten Commit anschauen / verstehen und dann Squash & Merge mit commit "VAG-6: ..." Ansonsten top 🎉

2023-04-08 12:51 UTC, biocarl commented
Bodos Clean Code requests habe ich gleich mitgemacht

2023-04-08 12:52 UTC, biocarl approved these changes

2023-04-11 06:44 UTC, merged